# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e55da9f2b06b00c16636b527da1411754fc8ad1c15d9caee0951d389ecddbe917de4e4de004a74f898061d2695925de18f01d10237798611107b047d78adae6d

test:
  secret_key_base: 6032b5cb95a5a8b32d43a63271d8482a8e35b5d0cdffe4889e85b63a91056a3a958bb51692b359c9dd40c80871cc9dba8e1c1e6fc42d74aa79a659dc19d5b209

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
